=== sgalrio0807/Lenguaje-de-marcas/Sergio_galan_AE_U5.1/Ejercicio_1/ejercicio1.dtd
<!ELEMENT sede (ubicacion, total_alumnos, ciclos_formativos, departamentos, docentes, alumnado)>
<!ATTLIST sede id_centro CDATA #REQUIRED>

<!ELEMENT ubicacion (#PCDATA)>
<!ELEMENT total_alumnos (#PCDATA)>

<!ELEMENT ciclos_formativos (ciclo+)>

<!ELEMENT ciclo (nombre, modulos)>
<!ATTLIST ciclo id CDATA #REQUIRED>

<!ELEMENT modulos (modulo+)>

<!ELEMENT modulo (nombre, num_horas, periodo_academico, nota)>
<!ATTLIST modulo id CDATA #REQUIRED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT num_horas (#PCDATA)>
<!ELEMENT periodo_academico (#PCDATA)>
<!ELEMENT nota (#PCDATA)>

<!ELEMENT departamentos (departamento+)>

<!ELEMENT departamento (nombre, jefe?, aulas?)>
<!ATTLIST departamento id CDATA #REQUIRED>

<!ELEMENT jefe (#PCDATA)>
<!ELEMENT aulas (aula+)>
<!ELEMENT aula (#PCDATA)>

<!ELEMENT docentes (docente+)>
<!ELEMENT docente EMPTY>
<!ATTLIST docente id CDATA #REQUIRED>

<!ELEMENT alumnado (alumno+)>

<!ELEMENT alumno (nombre, edad, ciclos, curso, dni?)>
<!ATTLIST alumno id CDATA #REQUIRED>

<!ELEMENT ciclos (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT curso (#PCDATA)>
<!ELEMENT dni (#PCDATA)>

=== sgalrio0807/Lenguaje-de-marcas/Sergio_galan_AE_U5.1/Ejercicio_1/ejercicio1.2.xml
<?xml version="1.0" encoding="ISO-8859-15"?>
<!DOCTYPE sede SYSTEM "ejercicio1.dtd">
<sede id_centro="050">

    <ubicacion>Santiponce</ubicacion>
    <total_alumnos>355</total_alumnos>

    <ciclos_formativos>

        <ciclo id="cocina">
            <nombre>Cocina</nombre>
            <modulos>
                <modulo id="verduras">
                    <nombre>Verduras</nombre>
                    <num_horas>200</num_horas>
                    <periodo_academico>24/25</periodo_academico>
                    <nota>7</nota>
                </modulo>
                <modulo id="pasta">
                    <nombre>pasta</nombre>
                    <num_horas>180</num_horas>
                    <periodo_academico>24/25</periodo_academico>
                    <nota>8</nota>
                </modulo>
            </modulos>
        </ciclo>

    </ciclos_formativos>

    <departamentos>

        <departamento id="frutas">
            <nombre>Departamento de fruta</nombre>
            <jefe>Antonio Pérez</jefe>
            <aulas>
                <aula>12</aula>
                <aula>14</aula>
            </aulas>
        </departamento>

        <departamento id="procesados">
            <nombre>Departamento de procesados</nombre>
        </departamento>

        <departamento id="bolleria">
            <nombre>Departamento de bolleria</nombre>
        </departamento>

    </departamentos>

    <docentes>
        <docente id="profesor1"/>
        <docente id="profesor2"/>
    </docentes>

    <alumnado>

        <alumno id="alumno 1">
            <nombre>Perico</nombre>
            <edad>21</edad>
            <ciclos>Cocina</ciclos>
            <curso>1</curso>
            <dni>44556677X</dni>
        </alumno>

        <alumno id="alumno 2">
            <nombre>Pepe</nombre>
            <edad>32</edad>
            <ciclos>Cocina</ciclos>
            <curso>2</curso>
        </alumno>

    </alumnado>

</sede>

=== sgalrio0807/Lenguaje-de-marcas/Sergio_galan_AE_U5.1/Ejercicio_1/ejercicio1.xml
<?xml version="1.0" encoding="ISO-8859-15"?>
<!DOCTYPE sede SYSTEM "ejercicio1.dtd">
<sede id_centro="001">
    
    <ubicacion>La Algaba</ubicacion>
    <total_alumnos>250</total_alumnos>
    <!-- Aquí comienzan dos ciclos-->
    <ciclos_formativos>
        <!-- Primer ciclo-->
        <ciclo id="dam">
            <nombre>Desarrollo de Aplicaciones Multiplataforma</nombre>
            <modulos>
                <modulo id="programacion">
                    <nombre>Programación</nombre>
                    <num_horas>260</num_horas>
                    <periodo_academico>25/26</periodo_academico>
                    <nota>10</nota>
                </modulo>
                <modulo id="base de datos">
                    <nombre>Bases de Datos</nombre>
                    <num_horas>230</num_horas>
                    <periodo_academico>25/26</periodo_academico>
                    <nota>8</nota>
                </modulo>
                <modulo id="lenguaje de marcas">
                    <nombre>Lenguaje de Marcas</nombre>
                    <num_horas>155</num_horas>
                    <periodo_academico>25/26</periodo_academico>
                    <nota>6</nota>
                </modulo>
            </modulos>
        </ciclo>
        <!-- Segundo ciclo-->
        <ciclo id="deporte">
            <nombre>Deporte</nombre>
            <modulos>
                <modulo id="individuales">
                    <nombre>Individuales</nombre>
                    <num_horas>300</num_horas>
                    <periodo_academico>24/25</periodo_academico>
                    <nota>9</nota>
                </modulo>
                <modulo id="colectivos">
                    <nombre>Colectivos</nombre>
                    <num_horas>210</num_horas>
                    <periodo_academico>24/25</periodo_academico>
                    <nota>7</nota>
                </modulo>
                <modulo id="valoracion">
                    <nombre>Valoración</nombre>
                    <num_horas>140</num_horas>
                    <periodo_academico>24/25</periodo_academico>
                    <nota>10</nota>
                </modulo>
            </modulos>
        </ciclo>

    </ciclos_formativos>
    <!--Departamentos y sus datos-->
    <departamentos>
        <departamento id="informatica">
            <nombre>Informática</nombre>
            <jefe>Javi Prada</jefe>
            <aulas>
                <aula>22</aula>
                <aula>23</aula>
            </aulas>
        </departamento>

        <departamento id="matematicas">
            <nombre>Matemáticas</nombre>
        </departamento>
    </departamentos>
    <!-- Docentes y alumnos-->
    <docentes>
        <docente id="docente1"/>
        <docente id="docente2"/>
    </docentes>

    <alumnado>
        <alumno id="alumno1">
            <nombre>Isidro</nombre>
            <edad>22</edad>
            <ciclos>dam</ciclos>
            <curso>1</curso>
            <dni>12345678A</dni>
        </alumno>

        <alumno id="alumno2">
            <nombre>Enrique</nombre>
            <edad>55</edad>
            <ciclos>deporte</ciclos>
            <curso>4</curso>
        </alumno>
    </alumnado>

</sede>
