=== sgalrio0807/Lenguaje-de-marcas/Sergio_galan_AE_U5.1/Ejercicio_3/ejercicio3.dtd
<!ELEMENT sistema (tiendas, proveedores, empleados, clientes, moviles, ventas)>

<!ELEMENT tiendas (tienda+)>
<!ELEMENT tienda (nombre, localidad)>
<!ATTLIST tienda id CDATA #REQUIRED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>

<!ELEMENT proveedores (proveedor+)>
<!ELEMENT proveedor (nombre, pais)>
<!ATTLIST proveedor id CDATA #REQUIRED>

<!ELEMENT pais (#PCDATA)>

<!ELEMENT empleados (empleado+)>
<!ELEMENT empleado (nombre, puesto)>
<!ATTLIST empleado id CDATA #REQUIRED>

<!ELEMENT puesto (#PCDATA)>

<!ELEMENT clientes (cliente+)>
<!ELEMENT cliente (nombre, tipo)>
<!ATTLIST cliente id CDATA #REQUIRED>

<!ELEMENT tipo (#PCDATA)>

<!ELEMENT moviles (movil+)>
<!ELEMENT movil (marca, modelo, precio)>
<!ATTLIST movil id CDATA #REQUIRED>

<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

<!ELEMENT ventas (venta+)>
<!ELEMENT venta (movil_ref, cliente_ref, empleado_ref, tienda_ref, fecha)>
<!ATTLIST venta id CDATA #REQUIRED>

<!ELEMENT movil_ref (#PCDATA)>
<!ELEMENT cliente_ref (#PCDATA)>
<!ELEMENT empleado_ref (#PCDATA)>
<!ELEMENT tienda_ref (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>

=== sgalrio0807/Lenguaje-de-marcas/Sergio_galan_AE_U5.1/Ejercicio_3/ejercicio3.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sistema SYSTEM "ejercicio3.dtd">

<sistema>

    <!-- Tiendas del cliente -->
    <tiendas>
        <tienda id="tienda1">
            <nombre>Tienda iphone</nombre>
            <localidad>camas</localidad>
        </tienda>

        <tienda id="tienda2">
            <nombre>tienda huawei</nombre>
            <localidad>Santiponce</localidad>
        </tienda>
    </tiendas>

    <!-- Proveedores -->
    <proveedores>
        <proveedor id="proveedor1">
            <nombre>Proveedor de macs</nombre>
            <pais>China</pais>
        </proveedor>

        <proveedor id="proveedor2">
            <nombre>Google</nombre>
            <pais>Estados Unidos</pais>
        </proveedor>
    </proveedores>

    <!-- Empleados -->
    <empleados>
        <empleado id="empleado1">
            <nombre>Sergio</nombre>
            <puesto>Encargado</puesto>
        </empleado>

        <empleado id="empleado2">
            <nombre>Marcos</nombre>
            <puesto>Vendedor</puesto>
        </empleado>
    </empleados>

    <!-- Clientes -->
    <clientes>
        <cliente id="cliente1">
            <nombre>Juan José</nombre>
            <tipo>Particular</tipo>
        </cliente>

        <cliente id="cliente2">
            <nombre>Angela</nombre>
            <tipo>Particular</tipo>
        </cliente>
    </clientes>

    <!-- Móviles -->
    <moviles>

        <!-- Android puro -->
        <movil id="movil1">
            <marca>Samsung</marca>
            <modelo>S23</modelo>
            <precio>799</precio>
        </movil>

        <!-- Android gama media -->
        <movil id="movil2">
            <marca>Realme</marca>
            <modelo>Realme 11 Pro</modelo>
            <precio>399</precio>
        </movil>

    </moviles>

    <!-- Ventas -->
    <ventas>

        <!-- Venta en La Algaba -->
        <venta id="venta1">
            <movil_ref>movil1</movil_ref>
            <cliente_ref>cliente1</cliente_ref>
            <empleado_ref>empleado1</empleado_ref>
            <tienda_ref>tienda1</tienda_ref>
            <fecha>2026-03-02</fecha>
        </venta>

        <!-- Venta en Santiponce -->
        <venta id="venta2">
            <movil_ref>movil2</movil_ref>
            <cliente_ref>cliente2</cliente_ref>
            <empleado_ref>empleado2</empleado_ref>
            <tienda_ref>tienda2</tienda_ref>
            <fecha>2026-03-05</fecha>
        </venta>

    </ventas>

</sistema>
